name: Update Air Quality Data

on:
  schedule:
    - cron: "*/5 * * * *"   # ogni 5 minuti
  workflow_dispatch:

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch raw data from Sensor.Community
        run: |
            curl -s https://data.sensor.community/airrohr/v1/sensor/53269/ -o data/raw-data.json

      - name: Commit and push if changed
        run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add data/raw-data.json
            git diff --quiet && git diff --staged --quiet || git commit -m "Auto update air quality data"
            git push